version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --cov=. --cov-report=xml --junitxml=coverage/pytest/junit.xml
            ls coverage/backend
      - store_test_results:
          path: coverage
      - persist_to_workspace:
          root: coverage
          paths:
            - backend
  upload_coverage:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - attach_workspace:
          at: coverage
      - run:
          name: upload reports
          command: |
            ls
            ls coverage
            ls coverage/backend
            bash <(wget -q -O - https://codecov.io/bash) -c -F backend -s coverage/backend
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - upload_coverage:
        requires:
          - build
